### ISSUE TITLE
Cygwin build fails due to \r in script

### ISSUE THREAD

**Issue by joebo** [tlack/xxl#3]
Building under cygwin 

$ uname -a
CYGWIN_NT-6.1 PFP-0137 1.7.35(0.287/5/3) 2015-03-04 12:09 x86_64 Cygwin

```
$ ./c
./c: line 13: $'\r': command not found
./c: line 16: $'\r': command not found
./c: line 19: $'\r': command not found
./c: line 81: syntax error near unexpected token `&&'
'/c: line 81: ` && \
```

I was able to build it successfully after:
cat c | dos2unix.exe  > c

./c

**Comment by tlack** [comment]
Hmm. Do you have your version of git setup to add DOS line endings by default? I'm in a similar environment:

```
$ uname -a
CYGWIN_NT-6.3 tlackpro3 2.4.1(0.293/5/3) 2016-01-24 11:26 x86_64 Cygwin
$ git --version
git version 2.7.4
```

and not seeing the \r's on a fresh checkout:

```
$ cat c | hexdump -c | grep '\\n' | wc -l
69
$ cat c | hexdump -c | grep '\\r' | wc -l
0
```

**Comment by tlack** [comment]
Same on Ubuntu with a fresh pull:

```
root@xxl ~/tmps/xxl () $ hexdump -c c | grep '\\r' | wc -l
0
root@xxl ~/tmps/xxl () $ hexdump -c c | grep '\\n' | wc -l
69
root@xxl ~/tmps/xxl () $ uname -a
Linux [XXXXX] 4.2.0-30-generic #36-Ubuntu SMP Fri Feb 26 00:58:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@xxl ~/tmps/xxl () $ git --version
git version 2.5.0
```

**Comment by joebo** [comment]
That is probably it. I think I just installed with defaults. Good to know.
I don't think anything is needed but it may be useful if someone runs
across it and searches the issues in the future.

Thanks

**Comment by tlack** [comment]
If you run into other issues under Windows, please let me know. 

There are some limitations regarding threading on that platform (no timed locks with the pthreads emulation stuff?), but I want to try to keep it in parity, especially after Microsoft's interesting Ubuntu announcement last week.

Thanks again
